# Docker compose file for bringing up a simple digital identity environment.

services:
  person:
    image: didemo-actors:latest
    entrypoint: /didemo-person
    ports:
      - "8000:80"
    restart: always
    environment:
      CONFIG_FILE: /person-config-file
      RUST_LOG: info
    configs:
      - person-config-file

  wallet:
    image: didemo-actors:latest
    entrypoint: /didemo-wallet
    ports:
      - "8001:80"
    restart: always
    environment:
      CONFIG_FILE: /wallet-config-file
      RUST_LOG: info
    configs:
      - wallet-config-file

  issuer-dmv:
    image: didemo-actors:latest
    entrypoint: /didemo-issuer
    ports:
      - "8002:80"
    restart: always
    environment:
      CONFIG_FILE: /issuer-dmv-config-file
      RUST_LOG: info
    configs:
      - issuer-dmv-config-file

  issuer-library:
    image: didemo-actors:latest
    entrypoint: /didemo-issuer
    ports:
      - "8003:80"
    restart: always
    environment:
      CONFIG_FILE: /issuer-library-config-file
      RUST_LOG: info
    configs:
      - issuer-library-config-file

configs:
  person-config-file:
    file: ../person/config/sample.yaml
  wallet-config-file:
    file: ../wallet/config/sample.yaml
  issuer-dmv-config-file:
    file: ../issuer/config/dmv.yaml
  issuer-library-config-file:
    file: ../issuer/config/library.yaml
